/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import { gql, useQuery } from '@apollo/client'
import withApollo from 'shared/libs/withApollo'
import { getDataFromTree } from '@apollo/client/react/ssr'
import { useEffect, useState } from 'react'
import { getMediumData } from 'services/medium'

const GET_GENERAL_SITE_OPTIONS = gql`
  query SiteGeneralOptions {
    myOptionsPage {
      siteGeneralOptions {
        logo {
          altText
          sourceUrl
        }
        socialLinks {
          socialLink {
            target
            title
            url
          }
        }
      }
    }    
  }
`

// type SocialLinksDataProps = {
//   socialLink: {
//     title: string
//     url: string
//     target: string
//   }
// }

// // type SocialLinksProps = {
// //   title: string
// //   url: string
// //   target: string
// // }

// // type LogoProps = {
// //   altText: string
// //   sourceUrl: string
// // }

// // type GeneralSiteOptionsProps  = {
// //   logo: LogoProps
// //   socialLinks: SocialLinksProps[] 
// // }

// // type DataProps = {
// //   data: GeneralSiteOptionsProps
// // }

  const pageContent = (data: any) => {   
    if (!data) return 

    return {
      logo: {
        altText: data?.myOptionsPage.siteGeneralOptions.logo.altText,
        sourceUrl: data?.myOptionsPage.siteGeneralOptions.logo.sourceUrl,
      },
      socialLinks : data?.myOptionsPage.siteGeneralOptions.socialLinks.map((socialLink: any) => {
        return {
          title: socialLink.socialLink.title,
          url: socialLink.socialLink.url,
          target: socialLink.socialLink.target,
        }
      })
    } 
  }

function getImages(string:string) {
  const imgRex = /<img.*?src="(.*?)"[^>]+>/g;
  const images = [];
    let img;
    while ((img = imgRex.exec(string))) {
        images.push(img[1]);
    }
  return images;
}
  


const Home = () => {
  const { data, loading } = useQuery(GET_GENERAL_SITE_OPTIONS);
  const [medium, setMedium] = useState([])
  const content = pageContent(data)

  useEffect(() => {
    const mediumData = async () => {
      const mediumData:any = await getMediumData()      
      setMedium(mediumData.data)
    }
    mediumData()
  }, [])

  if (!data && loading) {
    return <h1>Loading...</h1>
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Poc NextJS with Headless WP</h1>

      <img src={content?.logo.sourceUrl} width="100" alt={content?.logo.altText} />

      <hr />

      <ul>
        <li>LISTA DE POSTS MEDIUM</li>
        {medium.map((item: any) => {
          const paragraph:string = item['content:encoded'][0]
          const getImageInParagraph = getImages(paragraph)
          console.log()

          return (
            <li key={item.title}>
              <p><img src={getImageInParagraph[0]} width="150" alt="" /></p>
              <a href={item.link} target="_blank" rel="noreferrer">
                {item.title}                
              </a>
            </li>
          )
        })}
      </ul>

      <hr />

      <ul>
        {content?.socialLinks.map((socialLink:any, index: any) => (
          <li key={index}>
            <a href={socialLink.url} target={socialLink.target}>{socialLink.title}</a>
          </li>
        ))}
      </ul>
    </div>
  )
}

// export const getServerSideProps:GetServerSideProps = async () => {
//   const { data } = await client.query({
//     query: GET_GENERAL_SITE_OPTIONS,
//   });

//   const pageContent:GeneralSiteOptionsProps = {
//     logo: {
//       altText: data.myOptionsPage.siteGeneralOptions.logo.altText,
//       sourceUrl: data.myOptionsPage.siteGeneralOptions.logo.sourceUrl,
//     },
//     socialLinks : data.myOptionsPage.siteGeneralOptions.socialLinks.map((socialLink: SocialLinksDataProps) => {
//       return {
//         title: socialLink.socialLink.title,
//         url: socialLink.socialLink.url,
//         target: socialLink.socialLink.target,
//       }
//     }),
//   }

//   return {
//     props: {
//       data: pageContent
//     }
//  };
// }

// Home.getInitialProps = async (ctx: NextPageContext) => {
//   const mediumArticles = getMediumArticles({
//     auth: process.env.NEXT_PUBLIC_MEDIUM_TOKEN
//   })

//   const mediumContent = await mediumArticles

//   console.log(mediumContent)

//   return {
//     mediumContent
//   }
// }

export default withApollo(Home, { getDataFromTree })

